/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RpRouteImport } from './routes/rp'
import { Route as PtoRouteImport } from './routes/pto'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ObjectRouteImport } from './routes/object'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as GprRouteImport } from './routes/gpr'
import { Route as ForemanRouteImport } from './routes/foreman'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CommandRouteImport } from './routes/command'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalPeopleRouteImport } from './routes/portal.people'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalNewsRouteImport } from './routes/portal.news'
import { Route as ForemanMobileRouteImport } from './routes/foreman.mobile'

const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RpRoute = RpRouteImport.update({
  id: '/rp',
  path: '/rp',
  getParentRoute: () => rootRouteImport,
} as any)
const PtoRoute = PtoRouteImport.update({
  id: '/pto',
  path: '/pto',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const GprRoute = GprRouteImport.update({
  id: '/gpr',
  path: '/gpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ForemanRoute = ForemanRouteImport.update({
  id: '/foreman',
  path: '/foreman',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPeopleRoute = PortalPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewsRoute = PortalNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PortalRoute,
} as any)
const ForemanMobileRoute = ForemanMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => ForemanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/finance': typeof FinanceRoute
  '/foreman': typeof ForemanRouteWithChildren
  '/gpr': typeof GprRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/object': typeof ObjectRoute
  '/portal': typeof PortalRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/pto': typeof PtoRoute
  '/rp': typeof RpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply': typeof SupplyRoute
  '/foreman/mobile': typeof ForemanMobileRoute
  '/portal/news': typeof PortalNewsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/people': typeof PortalPeopleRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/finance': typeof FinanceRoute
  '/foreman': typeof ForemanRouteWithChildren
  '/gpr': typeof GprRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/object': typeof ObjectRoute
  '/portfolio': typeof PortfolioRoute
  '/pto': typeof PtoRoute
  '/rp': typeof RpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply': typeof SupplyRoute
  '/foreman/mobile': typeof ForemanMobileRoute
  '/portal/news': typeof PortalNewsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/people': typeof PortalPeopleRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/finance': typeof FinanceRoute
  '/foreman': typeof ForemanRouteWithChildren
  '/gpr': typeof GprRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/object': typeof ObjectRoute
  '/portal': typeof PortalRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/pto': typeof PtoRoute
  '/rp': typeof RpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supply': typeof SupplyRoute
  '/foreman/mobile': typeof ForemanMobileRoute
  '/portal/news': typeof PortalNewsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/people': typeof PortalPeopleRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/finance'
    | '/foreman'
    | '/gpr'
    | '/league'
    | '/login'
    | '/object'
    | '/portal'
    | '/portfolio'
    | '/pto'
    | '/rp'
    | '/sitemap.xml'
    | '/supply'
    | '/foreman/mobile'
    | '/portal/news'
    | '/portal/payments'
    | '/portal/people'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/finance'
    | '/foreman'
    | '/gpr'
    | '/league'
    | '/login'
    | '/object'
    | '/portfolio'
    | '/pto'
    | '/rp'
    | '/sitemap.xml'
    | '/supply'
    | '/foreman/mobile'
    | '/portal/news'
    | '/portal/payments'
    | '/portal/people'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/finance'
    | '/foreman'
    | '/gpr'
    | '/league'
    | '/login'
    | '/object'
    | '/portal'
    | '/portfolio'
    | '/pto'
    | '/rp'
    | '/sitemap.xml'
    | '/supply'
    | '/foreman/mobile'
    | '/portal/news'
    | '/portal/payments'
    | '/portal/people'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  FinanceRoute: typeof FinanceRoute
  ForemanRoute: typeof ForemanRouteWithChildren
  GprRoute: typeof GprRoute
  LeagueRoute: typeof LeagueRoute
  LoginRoute: typeof LoginRoute
  ObjectRoute: typeof ObjectRoute
  PortalRoute: typeof PortalRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  PtoRoute: typeof PtoRoute
  RpRoute: typeof RpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupplyRoute: typeof SupplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rp': {
      id: '/rp'
      path: '/rp'
      fullPath: '/rp'
      preLoaderRoute: typeof RpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pto': {
      id: '/pto'
      path: '/pto'
      fullPath: '/pto'
      preLoaderRoute: typeof PtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object': {
      id: '/object'
      path: '/object'
      fullPath: '/object'
      preLoaderRoute: typeof ObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpr': {
      id: '/gpr'
      path: '/gpr'
      fullPath: '/gpr'
      preLoaderRoute: typeof GprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreman': {
      id: '/foreman'
      path: '/foreman'
      fullPath: '/foreman'
      preLoaderRoute: typeof ForemanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/people': {
      id: '/portal/people'
      path: '/people'
      fullPath: '/portal/people'
      preLoaderRoute: typeof PortalPeopleRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/news': {
      id: '/portal/news'
      path: '/news'
      fullPath: '/portal/news'
      preLoaderRoute: typeof PortalNewsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/foreman/mobile': {
      id: '/foreman/mobile'
      path: '/mobile'
      fullPath: '/foreman/mobile'
      preLoaderRoute: typeof ForemanMobileRouteImport
      parentRoute: typeof ForemanRoute
    }
  }
}

interface ForemanRouteChildren {
  ForemanMobileRoute: typeof ForemanMobileRoute
}

const ForemanRouteChildren: ForemanRouteChildren = {
  ForemanMobileRoute: ForemanMobileRoute,
}

const ForemanRouteWithChildren =
  ForemanRoute._addFileChildren(ForemanRouteChildren)

interface PortalRouteChildren {
  PortalNewsRoute: typeof PortalNewsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalPeopleRoute: typeof PortalPeopleRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalNewsRoute: PortalNewsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalPeopleRoute: PortalPeopleRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  FinanceRoute: FinanceRoute,
  ForemanRoute: ForemanRouteWithChildren,
  GprRoute: GprRoute,
  LeagueRoute: LeagueRoute,
  LoginRoute: LoginRoute,
  ObjectRoute: ObjectRoute,
  PortalRoute: PortalRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  PtoRoute: PtoRoute,
  RpRoute: RpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupplyRoute: SupplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
